In [1]:
import pandas as pd
import numpy as np
data = ({'Letters':["A", "B", "A", "C", "B","F","F","F"],
       'Colors':['red','red','blue','black','black','red','blue','black'],
        'numbers' : [1,4,1325,42,124,1,7,8]
       })
df = pd.DataFrame(data)
print(df)
column_names = df.columns.tolist()
print(column_names)
################################################

print(df)

  Letters Colors  numbers
0       A    red        1
1       B    red        4
2       A   blue     1325
3       C  black       42
4       B  black      124
5       F    red        1
6       F   blue        7
7       F  black        8
['Letters', 'Colors', 'numbers']
  Letters Colors  numbers
0       A    red        1
1       B    red        4
2       A   blue     1325
3       C  black       42
4       B  black      124
5       F    red        1
6       F   blue        7
7       F  black        8

In [2]:
##onehot me category ko amount of variable me split krke column bnao
##ordinal me manually daal do 
#ABCF == Category1 ,2,3 4
column_names = df.columns.tolist()
for col in column_names:
    if df[col].dtype == object:
        print("yes")
    else:
        print ("no")
        
def ordinal_encoding(df):
    df['Letters'] = df['Letters'].map({'A': 1, 'B': 2, 'C': 3, 'F': 4})
    df['Colors'] = df['Colors'].map({'red': 1, 'blue': 2, 'black': 3})
    return df
df = ordinal_encoding(df)
print(df)
#column_type = df['Letters'].dtype
##print("Data type of 'Category' column:", column_type)

yes
yes
no
   Letters  Colors  numbers
0        1       1        1
1        2       1        4
2        1       2     1325
3        3       3       42
4        2       3      124
5        4       1        1
6        4       2        7
7        4       3        8